export const firebaseConfig = {
  projectId: process.env.FIREBASE_PID,
  privateKey: process.env.FIREBASE_PRIVATE_KEY,
  privateId: process.env.FIREBASE_PRIVATE_ID,
  clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
  clientId: process.env.FIREBASE_CLIENT_ID,
  authUrl: process.env.FIREBASE_AUTH_URL,
  tokenUrl: process.env.FIREBASE_TOKEN_URL,
  authProviderX509CertUrl: process.env.FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
  clientX509CertUrl: process.env.FIREBASE_CLIENT_X509_CERT_URL,
  appId: process.env.FIREBASE_AID,
  databaseURL: process.env.FIREBASE_DB,
  storageBucket: process.env.FIREBASE_STORAGE,
  locationId: process.env.FIREBASE_LID,
  apiKey: process.env.FIREBASE_API_KEY,
  authDomain: process.env.FIREBASE_AUTH_DOMAIN,
  messagingSenderId: process.env.FIREBASE_SID,
  measurementId: process.env.FIREBASE_MID,
};
